from typing_extensions import final
@final
class alsreceiver():
	@property
	def version(self) -> str: ...

	@property
	def connect(self, address:str, port:str) -> bool: ...

	@property
	def receive(self, unused:int) -> int: ...

	@property
	def receive_async(self, mode:int) -> tuple[int, int]: ...

	@property
	def receive_get(self, unused:int) -> int | None: ...

	@property
	def get_next_id(self) -> int: ...

	@property
	def get_data(self, id:int) -> memoryview | None: ...

	@property
	def free_by_id(self, id:int, wait_if_locked:bool=True) -> bool: ...

	@property
	def free(self, view:memoryview, wait_if_locked:bool=True) -> bool: ...

	@property
	def set_timeouts(self, connect:float, receive:float, receive_frag:float, send:float) -> bool: ...

	@property
	def disconnect(self): ...
	
	@property
	def send(self, data:memoryview | bytes) -> bool: ...